SoftEng/WiLearn/WiLearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('login.urls', namespace='login')),
    path('dashboard/', include('lms.urls', namespace='lms')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SoftEng/WiLearn/lms/urls.py
from django.urls import path
from . import views


app_name = 'lms'
urlpatterns = [
  path('', views.dashboard, name='dashboard'),
  path('inbox/', views.inbox, name='inbox'),
  path('add_course/', views.add_course, name='add_course'),
  path('create_announcement/', views.post_announcements, name='create_announcements'),
  path('profile/', views.profile, name='profile'),

  # path('logout/', views.logout_user),
  # path('courses/', views.courses, name='courses'),
]

SoftEng/WiLearn/login/urls.py
from django.urls import path
from . import views


app_name = 'login'
urlpatterns = [
  path('', views.main, name='main'),
  path('courses/', views.courses, name='courses'),
]

SoftEng/WiLearn/login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class Teachers(AbstractUser):
    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=255, default="")
    last_name = models.CharField(max_length=255, default="")
    department = models.CharField(max_length=255, default="")

    REQUIRED_FIELDS = ['email']


    def save(self, *args, **kwargs):
        if len(self.password) <= 20:
            self.set_password(self.password)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.get_full_name()} || {self.department}"

SoftEng/WiLearn/login/forms.py
from django import forms
from .models import Teachers


class LoginForm(forms.Form):
    email = forms.CharField(label="Email", widget=forms.TextInput(attrs={'id': "email", 'name': 'email'}))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'id': "password", 'name': 'password'}))

    class Meta:
        model = Teachers
        fields = ['email', 'password']

SoftEng/WiLearn/login/extra/views.py
# from django.contrib.auth.decorators import login_required
# from django.http import HttpResponseRedirect
# from django.shortcuts import render, redirect
# from django.contrib.auth import login
# from django.contrib import messages
# from .backends import EmailBackend
# from .forms import LoginForm
# # from lms.views import dashboard
# from django.conf import settings
# from django.urls import reverse
#
# # Create your views here.
#
#
# def main(request):
#     next_param = request.POST.get('next', 'lms:dashboard')
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             email = form.cleaned_data['email']
#             password = form.cleaned_data['password']
#             user = EmailBackend().authenticate(request, username=email, password=password)
#             if user:
#                 print(f"USER:{user}")
#                 login(request, user=user, backend='login.backends.EmailBackend')
#                 print(request.user.is_authenticated)
#                 return redirect(next_param)
#                 # return render(request, 'lms/dashboard.html')
#
#         else:
#             return render(request, 'login/index.html', {'form': form})
#             #CONCERN: SINCE POPUP NOT SURE PAANO IPAPAKITA NA MAY ERROR SA FORMS
#     else:
#         form = LoginForm()
#         return render(request, 'login/index.html', {'form': form, 'next': next_param})
#
#
# def courses(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             email = form.cleaned_data['email']
#             password = form.cleaned_data['password']
#             user = EmailBackend().authenticate(request, username=email, password=password)
#             if user:
#                 login(request, user=user, backend='login.backends.EmailBackend')
#                 return redirect('lms:dashboard')
#         else:
#             form = LoginForm()
#             messages.error(request, 'Invalid login credentials. Please try again.')
#             return render(request, 'login/index.html', {'form': form})
#
#     form = LoginForm()
#     return render(request, 'login/index.html', {'form': form})
#
#
#

SoftEng/WiLearn/login/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib import messages
from .backends import EmailBackend
from .forms import LoginForm
from django.conf import settings
from django.urls import reverse



# Create your views here.
def main(request):
    next_param = request.GET.get('next', reverse('lms:dashboard'))
    print(f"Auth: {request.user.is_authenticated}")

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = EmailBackend().authenticate(request, username=email, password=password)
            if user is not None:
                print(f"USER:{user}")
                login(request, user=user, backend='login.backends.EmailBackend')
                print(request.user.is_authenticated)
                return redirect(next_param)

        else:
            return render(request, 'login/index.html', {'form': form})
            # CONCERN: SINCE POPUP NOT SURE PAANO IPAPAKITA NA MAY ERROR SA FORMS
    else:
        form = LoginForm()
        return render(request, 'login/index.html', {'form': form})



def courses(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = EmailBackend().authenticate(request, username=email, password=password)
            if user:
                login(request, user=user, backend='login.backends.EmailBackend')
                return redirect('lms:dashboard')
        else:
            form = LoginForm()
            messages.error(request, 'Invalid login credentials. Please try again.')
            return render(request, 'login/index.html', {'form': form})

    form = LoginForm()
    return render(request, 'login/index.html', {'form': form})

SoftEng/WiLearn/login/templates/login/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Kadwa&family=Langar&family=Lato:wght@100;300&family=REM&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'login/images/logo.png' %}" type="image/png">
    <title>Wawawi</title>
    <link rel="stylesheet" href="{% static 'login/css/styles.css' %}">
</head>
<body>
    <header>
        <nav>
            <div class="left-nav">
                <div class="logo">
                    <a href="{% url 'login:main' %}">
                        <img class="logo" src="{% static 'login/images/logo.png' %}" alt="Wawawi">
                    </a>
                </div>

                <ul>
                    <li><a href="{% url 'login:main' %}#about">ABOUT</a></li>
                    <li><a href="{% url 'login:main' %}#offers">OFFERS</a></li>
                    <li><a href="{% url 'login:courses' %}">COURSES</a></li>
                    {% if user.is_authenticated %}
                        <li><h2>{{user.username}}</h2></li>
                    {% endif %}
                </ul>
            </div>
            <div class="right-nav">
                <a href="#" class="button" onclick="openLoginPopup()" >Wi-Learn</a>
            </div>
        </nav>
    </header>

    <div id="loginPopup" class="popup">
        <div class="popup-content">
            <div class="top">
            <img src="{% static 'login/images/logo.png' %}" alt="Your Logo">
            <h2>Wawawi</h2>
            <span class="close" onclick="closeLoginPopup()">&times;</span>
             </div>

            <form method="post" action="{% url 'login:main'%}">
                {% csrf_token %}

                {{ form.email.label_tag }}
                {{ form.email }}
                {% if form.errors %}
                    <p>{{ form.errors }}<p>
                {% endif %}
                <div class="password-container">
                    {{ form.password.label_tag }}
                    <i class="fa-solid fa-eye" id="eye" onclick="togglePasswordVisibility()"></i>
                    {{ form.password }}
                </div>

                <input type="hidden" name="next" value="{{ next }}">

                <button type="submit" class="signin-button">Sign In</button>
            </form>
            <p class="forgot-password">Forgot Password?</p>
        </div>
    </div>

    <div class="rectangle">
    </div>

    <div class="next1">
        <p>Learn now with Wawawi, an interactive learning website for students and professors</p>
        <button>Enroll Now</button>
    </div>

    {% block content %} {% endblock %}
    <script src="{% static 'login/js/scripts.js' %}">
    </script>
</body>
</html>