SoftEng/WiLearn/WiLearn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('login.urls', namespace='login')),
    path('dashboard/', include('lms.urls', namespace='lms')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SoftEng/WiLearn/lms/urls.py
from django.urls import path
from . import views


app_name = 'lms'
urlpatterns = [
  path('', views.dashboard, name='dashboard'),
  path('inbox/', views.inbox, name='inbox'),
  path('add_course/', views.add_course, name='add_course'),
  path('create_announcement/', views.post_announcements, name='create_announcements'),
  path('profile/', views.profile, name='profile'),

  # path('logout/', views.logout_user),
  # path('courses/', views.courses, name='courses'),
]

SoftEng/WiLearn/lms/models.py
from django.conf import settings
from django.db import models
from django_quill.fields import QuillField


# Create your models here.
class Announcements(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    text = QuillField()


class Courses(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course_id = models.CharField(unique=True,max_length=255)
    img = models.ImageField(upload_to='images/')
    name = models.CharField(max_length=255)
    desc = models.TextField(max_length=255)
    enrollment_start = models.DateField()
    enrollment_end = models.DateField()
    course_start = models.DateField()
    course_end = models.DateField()
    lab_time = models.CharField(max_length=255)
    lab_day = models.CharField(max_length=255)
    lecture_time = models.CharField(max_length=255)
    lecture_day = models.CharField(max_length=255)

SoftEng/WiLearn/lms/forms.py
from django import forms
from .models import Announcements, Courses
from django_quill.forms import QuillFormField


class AnnouncementForm(forms.ModelForm):
    Announcement_Title = forms.CharField()
    Announcement_Content = QuillFormField()
    # text = forms.CharField(widget=forms.Textarea(attrs={'id':'quill-editor'}))

    class Meta:
        model = Announcements
        fields = ['Announcement_Title', 'Announcement_Content']


class CourseForm(forms.ModelForm):
    class Meta:
        model = Courses
        fields = ('img',
                  'name',
                  'desc',
                  'enrollment_start',
                  'enrollment_end',
                  'course_start',
                  'course_end',
                  'lab_time',
                  'lab_day',
                  'lecture_time',
                  'lecture_day',)
        exclude = ['user']
        labels = {
            "img": "Course Image",
            "name": "Course Name",
            "desc": "Course Description",
            "enrollment_start": "Enrollment Start Date",
            "enrollment_end": "Enrollment End Date",
            "course_start": "Course Start Date",
            "course_end": "Course End Date",
            "lab_time": "Laboratory Time",
            "lab_day": "Laboratory Day",
            "lecture_time": "Lecture Time",
            "lecture_day": "Lecture Day",
        }

        widgets = {
            "img": forms.FileInput(attrs={'id': "courseImage"}),
            "name": forms.TextInput(attrs={'id': "courseName"}),
            "desc": forms.Textarea(attrs={'id': "courseDescription"}),
            "enrollment_start": forms.DateInput(attrs={'id': "enrollmentStartDate",'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)'}),
            "enrollment_end": forms.DateInput(attrs={'id': "enrollmentEndDate",'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)'}),
            "course_start": forms.DateInput(attrs={'id': "courseStartDate",'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)'}),
            "course_end": forms.DateInput(attrs={'id': "courseEndDate",'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)'}),"lab_time": forms.TextInput(attrs={'id': "labTime"}),
            "lab_day": forms.TextInput(attrs={'id': "labDay"}),
            "lecture_time": forms.TextInput(attrs={'id': "lectureTime"}),
            "lecture_day": forms.TextInput(attrs={'id': "lectureDay"}),
        }

SoftEng/WiLearn/lms/views.py
from django.shortcuts import render, redirect
from .forms import AnnouncementForm, CourseForm
from .models import Announcements, Courses
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from random import randint
from PIL import Image

# Create your views here.
User = get_user_model()
COMPARISON_DICT = {10: "00000", 100: "0000", 1000: "000", 10000: "00", 100000: "0"}

@login_required
def dashboard(request):
    print(request.user.is_authenticated)
    user = request.user
    print(user.id)
    course = Courses.objects.filter(user_id=user.id)
    return render(request, 'lms/dashboard.html', {'course': course})


@login_required
def inbox(request):
    return render(request, 'lms/inbox.html')


@login_required
def post_announcements(request):
    if request.method == 'POST':
        announcement_form = AnnouncementForm(request.POST)
        if announcement_form.is_valid():
            title = announcement_form.cleaned_data['Announcement_Title']
            text = announcement_form.cleaned_data['Announcement_Content']
            print(f"{title} + {text}")
            a = Announcements(title=title, text=text)
            a.save()
            return redirect('dashboard')
        else:
            print(announcement_form)
            print(announcement_form.errors)

    form = AnnouncementForm()
    return render(request, 'lms/postannouncement.html', {'form': form})

    # return render(request, 'lms/postannouncement.html', {'form': form})


@login_required
def add_course(request):
    if request.method == 'POST':
        course_form = CourseForm(request.POST, request.FILES)
        print("HEELO")
        if course_form.is_valid():
            user = request.user
            teacher = User.objects.get(email=user.email)
            if teacher is not None:
                last = Courses.objects.all().last()
                last.id += 1
                course = course_form.save(commit=False)
                course.user = teacher
                for key, val in COMPARISON_DICT.items():
                    if last.id < key:
                        course.course_id = f"{teacher.last_name}.{val}{last.id}"
                        break
                    elif last.id >= 100000:
                        course.course_id = f"{teacher.last_name}.{last.id}"
                        break
                course.save()

            return redirect('lms:dashboard')
        else:
            print(course_form)
            print(course_form.errors)

    form = CourseForm()
    return render(request, 'lms/addcourse.html', {'form': form})


@login_required
def profile(request):
    return render(request, 'lms/profile.html')

SoftEng/WiLearn/lms/templates/lms/addcourse.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Kadwa&family=Langar&family=Lato:wght@100;300&family=REM&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'lms/css/dashboard.css' %}">
    <link rel="icon" href="{% static 'lms/images/logo.png' %}" type="image/png">
    <title>Wawawi</title>
</head>
<body>

<!-- Side Navigation Bar -->
<nav class="sidenav">
    <ul>
        <li>
            <a href="{% url 'lms:dashboard' %}">
                <img class="logo" src="{% static 'lms/images/logo.png' %}" alt="Your Logo">
            </a>
        </li>
        <li>
            <a href="{% url 'lms:profile' %}">
                <i class="fa fa-user"></i>
                <span>Profile</span>
            </a>
        </li>
        <li>
            <a href="{% url 'lms:dashboard' %}">
                <i class="fa fa-tachometer"></i>
                <span>Dashboard</span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-book"></i>
                <span>Courses</span>
            </a>
        </li>
        <li>
            <a href="activities.html">
                <i class="fa fa-calendar"></i>
                <span>Activities</span>
            </a>
        </li>
        <li>
            <a href="{% url 'lms:inbox' %}">
                <i class="fa fa-inbox"></i>
                <span>Inbox</span>
            </a>
        </li>
    </ul>
</nav>

<!-- Section Content -->
<section class="content">
    <div class="header-container">
        <h1 class="db">DASHBOARD</h1>
        <h1 class="wl">Wi-Learn</h1>
    </div>
</section>

<section class="course-creation">
    <h1>Create Course</h1>
    <hr>

    <form id="courseCreationForm" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <div class="form-group">
            {{ form.img.label_tag }}
            {{ form.img }}
        </div>
        <div class="form-group">
            {{ form.name.label_tag }}
            {{ form.name }}
        </div>
        <div class="form-group">
            {{ form.desc.label_tag }}
            {{ form.desc }}
        </div>

        <div class="form-grid-container">
            <div class="form-group">
                {{ form.enrollment_start.label_tag }}
                {{ form.enrollment_start }}
            </div>
            <div class="form-group">
                {{ form.enrollment_end.label_tag }}
                {{ form.enrollment_end }}
            </div>
            <div class="form-group">
                {{ form.course_start.label_tag }}
                {{ form.course_start }}
            </div>
            <div class="form-group">
                {{ form.course_end.label_tag }}
                {{ form.course_end }}
            </div>
            <div class="form-group">
                {{ form.lab_time.label_tag }}
                {{ form.lab_time }}
            </div>
            <div class="form-group">
                {{ form.lab_day.label_tag }}
                {{ form.lab_day }}
            </div>

            <div class="form-group">
                {{ form.lecture_time.label_tag }}
                {{ form.lecture_time }}
            </div>
            <div class="form-group">
                {{ form.lecture_day.label_tag }}
                {{ form.lecture_day }}
            </div>
        </div>
    <hr>
    <div class="button-containers">
        <button class="cancel-button" onclick="discardCourse()">Cancel</button>
        <button class="save-button">Save</button>
        <button class="publish-button">Publish</button>
    </div>
    </form>
</section>

<script src="{% static 'lms/js/dashboard.js' %}"></script>
</body>
</html>

SoftEng/WiLearn/lms/templates/lms/dashboard.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Kadwa&family=Lato:wght@100;300&family=REM&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'lms/css/dashboard.css' %}">
    <link rel="icon" href="{% static 'lms/images/logo.png' %}" type="image/png">
    <title>Wawawi</title>
</head>
<body>

<!-- Side Navigation Bar -->
<nav class="sidenav">
    <ul>
        <li>
            <a href="{% url 'lms:dashboard' %}">
                <img class="logo" src="{% static 'lms/images/logo.png' %}" alt="Your Logo">
            </a>
        </li>
        <li>
            <a href="{% url 'lms:profile' %}">
                <i class="fa fa-user"></i>
                <span>Profile</span>
            </a>
        </li>
        <li>
            <a href="{% url 'lms:dashboard' %}">
                <i class="fa fa-tachometer"></i>
                <span>Dashboard</span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-book"></i>
                <span>Courses</span>
            </a>
        </li>
        <li>
            <a href="activities.html">
                <i class="fa fa-calendar"></i>
                <span>Activities</span>
            </a>
        </li>
        <li>
            <a href="{% url 'lms:inbox' %}">
                <i class="fa fa-inbox"></i>
                <span>Inbox</span>
            </a>
        </li>
    </ul>
</nav>

<!-- Section Content -->
<section class="content">
    <div class="header-container">
        <h1 class="db">DASHBOARD</h1>
        {% if user.is_authenticated %}
            <h2>{{user.username}}</h2>
        {% endif %}
        <h1 class="wl">Wi-Learn</h1>
    </div>
</section>

<section class="dashboard-content">
    <div class="button-container">
        <div class="course-buttons">
            <button id="activeButton" onclick="toggleCourses('active')">
                Active Courses
            </button>
            <button id="inactiveButton" onclick="toggleCourses('inactive')">
                Inactive Courses
            </button>
        </div>
        <button id="addCourseButton" class="add-course-button" title="Add Course">+</button>
    </div>
    <hr>

<section class="courses-section">
    <div id="activeCourses" class="courses">
        <!-- Add your active course content here -->
        <div class="course-grid">
            <div class="course">
                <img src="{% static 'lms/images/offer.png' %}" alt="Course 2">
                <p class="course-id">Course ID: 67890</p>
                <p class="course-name">Course Name: Web Development</p>
                <p>Time</p>
                <p>date</p>
            </div>

            {% if course %}
                {% for c in course %}
                <div class="course">
                    <img src="{% get_media_prefix %}{{ c.img }}" alt="Course 2">
                    <p class="course-id">Course ID: {{ c.course_id }}</p>
                    <p class="course-name">Course Name: {{ c.name }}</p>
                    <p>Time</p>
                    <p>date</p>
                </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div id="inactiveCourses" class="courses">
        <div class="course-grid">
            <div class="course">
                <img src="{% static 'lms/images/offer.png' %}" alt="Course 1">
                <p class="course-id">Course ID: 12345</p>
                <p class="course-name">Course Name: Introduction to Programming</p>
            </div>
        </div>
    </div>
</section>

<section class="announcements">
    <div class="announcement-title">
        <h2 class="ann">Posted Announcements</h2>
    </div>
    <div class="post-announcement-button">
        <button id="postAnnouncementButton" title="Post Announcements" onclick="navigateToPostAnnouncement()">+</button>
    </div>
</section>

<hr>

<section>
    <div class="announcements-content">
        <div class="announcement">
            <h3 class="announcement-title">Announcement 1</h3>
            <p class="announcement-description">Description for Announcement 1.Description for Announcement 1.Description for Announcement 1.Description for Announcement 1.Description for Announcement 1.Description for Announcement 1.Description for Announcement 1.</p>
        </div>
        <div class="announcement">
            <h3 class="announcement-title">Announcement 2</h3>
            <p class="announcement-description">Description for Announcement 2.</p>
        </div>
        <div class="announcement">
            <h3 class="announcement-title">Announcement 3</h3>
            <p class="announcement-description">Description for Announcement 3.</p>
        </div>

        {% if announcement %}
            {% for a in announcement %}
                <div class="announcement">
                    <h3 class="announcement-title">ANNOUNCEMENT: {{ a.title }}</h3>
                    <p class="announcement-description">{{ a.text.html| safe }}</p>
                </div>
            {% endfor %}
        {% endif %}

    </div>
</section>

</section>
<script src="{% static 'lms/js/dashboard.js' %}"></script>
</body>
</html>

SoftEng/WiLearn/lms/templates/lms/inbox.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Kadwa&family=Lato:wght@100;300&family=REM&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'lms/css/inbox.css' %}">
    <link rel="icon" href="{% static 'lms/images/logo.png' %}" type="image/png">
    <title>Wawawi</title>

</head>
<body>
    <!-- Side Navigation Bar -->
<nav class="sidenav">
    <ul>
        <li>
            <a href="{% url 'lms:dashboard' %}">
                <img class="logo" src="{% static 'lms/images/logo.png' %}" alt="Your Logo">
            </a>
        </li>
        <li>
            <a href="profile.html">
                <i class="fa fa-user"></i>
                <span>Profile</span>
            </a>
        </li>
        <li>
            <a href="{% url 'lms:dashboard' %}">
                <i class="fa fa-tachometer"></i>
                <span>Dashboard</span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-book"></i>
                <span>Courses</span>
            </a>
        </li>
        <li>
            <a href="activities.html">
                <i class="fa fa-calendar"></i>
                <span>Activities</span>
            </a>
        </li>
        <li>
            <a href="{% url 'lms:inbox' %}">
                <i class="fa fa-inbox"></i>
                <span>Inbox</span>
            </a>
        </li>
    </ul>
</nav>

<section class="content">
    <div class="header-container">
        <h1 class="db">DASHBOARD</h1>
        <h1 class="wl">Wi-Learn</h1>
    </div>
</section>

<section class="mail-content">
    <div class="mail-course-container">
        <div class="dropdown">
            <input onclick="mailCourseFunction()" type="text" placeholder="Course Search.." id="myInput" onkeyup="filterMailCourseFunction()">
              <div onclick="mailCourseFunction()" id="myDropdown" class="dropdown-content">
              <a href="#about">About</a>
              <a href="#base">Base</a>
              <a href="#blog">Blog</a>
              <a href="#contact">Contact</a>
              <a href="#custom">Custom</a>
              <a href="#support">Support</a>
              <a href="#tools">Tools</a>
            </div>
          </div> 
    </div>

    <div class="mail-inbox-container">
        <div class="dropdown2">
            <input onclick="myFunction2()" type="text" placeholder="Inbox Search.." id="myInput2" onkeyup="filterFunction2()">
              <div onclick="myFunction2()" id="myDropdown2" class="dropdown-content">
              <a href="#about">About</a>
              <a href="#base">Base</a>
              <a href="#contact">Contact</a>
              <a href="#custom">Custom</a>
              <a href="#support">Support</a>
              <a href="#tools">Tools</a>
            </div>
          </div> 
    </div>
</section>

<aside class="message-content">
    <article class="message-content-wrapper">
        <div class="message-item">
            <h2> Date</h2>
            <h1> Name</h1>
            <p> Lorem Ipsum</p>
        </div>
    </article>
    <article class="message-content-wrapper">
        <div class="message-item">
            <h2> Date</h2>
            <h1> Name</h1>
            <p> Lorem Ipsum</p>
        </div>
    </article>
    <article class="message-content-wrapper">
        <div class="message-item">
            <h2> Date</h2>
            <h1> Name</h1>
            <p> Lorem Ipsum</p>
        </div>
    </article>
    <article class="message-content-wrapper">
        <div class="message-item">
            <h2> Date</h2>
            <h1> Name</h1>
            <p> Lorem Ipsum</p>
        </div>
    </article>
    <article class="message-content-wrapper">
        <div class="message-item">
            <h2> Date</h2>
            <h1> Name</h1>
            <p> Lorem Ipsum</p>
        </div>
    </article>
    <article class="message-content-wrapper">
        <div class="message-item">
            <h2> Date</h2>
            <h1> Name</h1>
            <p> Lorem Ipsum</p>
        </div>
    </article>
    <article class="message-content-wrapper">
        <div class="message-item">
            <h2> Date</h2>
            <h1> Name</h1>
            <p> Lorem Ipsum</p>
        </div>
    </article>
</aside>
</body>

<script src="{% static 'lms/js/inbox.js' %}"></script>
</html>

SoftEng/WiLearn/lms/templates/lms/postannouncement.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    {{ form.media }}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Kadwa&family=Langar&family=Lato:wght@100;300&family=REM&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'lms/css/announcement.css' %}">
    <link rel="icon" href="{% static 'lms/images/logo.png' %}" type="image/png">
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <link href="https://cdn.quilljs.com/1.3.6/quill.fileUpload.css" rel="stylesheet">
    <script src="https://cdn.quilljs.com/1.3.6/quill.fileUpload.js"></script>
    <title>Wawawi</title>
</head>
<body>

<!-- Side Navigation Bar -->
<nav class="sidenav">
    <ul>
        <li>
            <a href="{% url 'lms:dashboard' %}">
                <img class="logo" src="{% static 'lms/images/logo.png' %}" alt="Your Logo">
            </a>
        </li>
        <li>
            <a href="profile.html">
                <i class="fa fa-user"></i>
                <span>Profile</span>
            </a>
        </li>
        <li>
            <a href="{% url 'lms:dashboard' %}">
                <i class="fa fa-tachometer"></i>
                <span>Dashboard</span>
            </a>
        </li>
        <li>
            <a href="#">
                <i class="fa fa-book"></i>
                <span>Courses</span>
            </a>
        </li>
        <li>
            <a href="activities.html">
                <i class="fa fa-calendar"></i>
                <span>Activities</span>
            </a>
        </li>
        <li>
            <a href="{% url 'lms:inbox' %}">
                <i class="fa fa-inbox"></i>
                <span>Inbox</span>
            </a>
        </li>
    </ul>
</nav>

<!-- Section Content -->
<section class="content">
    <div class="header-container">
        <h1 class="db">DASHBOARD</h1>
        <h1 class="wl">Wi-Learn</h1>
    </div>
</section>

<section class="announcement-creation">
    <h2>Create Announcement</h2>
    <div class="announcement-form">
        <form method="post">
            {% csrf_token %}
            {{ form }}

        <!-- Title input field
        <div class="form-group">
            <label for="announcementTitle">Announcement Title:</label>
            <input type="text" id="announcementTitle" name="announcementTitle" required>
        </div>
        
        Quill rich text editor for description
        <div class="form-group">
            <div id="announcement-editor" name="announcementText" required></div>
        </div>
        -->
        <hr>
        <button class="cancel-button" onclick="cancelAnnouncement()">Cancel</button>
        <button type="submit" class="publish-button">Publish</button>
        <!--        <button type="submit" class="publish-button" onclick="publishAnnouncement()">Publish</button> -->
        </form>
    </div>
</section>



<script src="{% static 'lms/js/announcement.js' %}"></script>
</body>
</html>